version: '3'
services:

#Creating the DNS Service
  dns:
    build: .
    image: azevedo.paulo/dns1:latest
    container_name: ns1.asa.br
    restart: unless-stopped
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
      - ./:/etc/bind