version: '3'
services:

#Creating the DNS Service
  dns:
    build: .
    image: azevedo.paulo/dns1:latest
    container_name: ns1.asa.br
    restart: unless-stopped
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    networks:
      dns-network:
        ipv4_address: 192.168.55.10

networks:
  dns-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24